# Generated by Django 6.1.1 on 2026-09-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('MANTENIMIENTO', 'En mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
